# Five Pillars JSON 
This is for Attendance

In [1]:
import pandas as pd
import json 
import numpy as np 
import _pickle as pickle
import math

In [2]:
# Pull in the df
df = pd.read_excel('Attendance and Payment April 2025.xlsx')
df

,Name,Paid,Worked,Attended,18+,CoC,Cabin Number,Decorated,Hours Worked,AP Earned,Role,UserID,Notes
0,Wes Holland,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,8.0,NaN
1,Maggie Holland,1.0,1.0,1.0,1.0,1.0,NaN,1.0,2.50,12.0,player,13.0,NaN
2,David Pautke,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,50.0,player,36.0,NaN
3,Shannon Thornhill,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,NaN,NaN
4,Samael Hamlet,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,41.0,NaN
5,Jessica Remick,1.0,1.0,1.0,1.0,1.0,NaN,1.0,7.00,40.0,player,33.0,NaN
6,Todd Ladrach,1.0,1.0,1.0,1.0,1.0,NaN,NaN,4.00,20.0,player,NaN,NaN
7,Clay Westman,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.25,11.0,player,3.0,NaN
8,Matt Cuna,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,5.0,NaN
9,Blake Casanova,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,28.0,NaN
10,Mike Warnock,1.0,1.0,NaN,1.0,1.0,NaN,NaN,0.00,0.0,player,NaN,NaN
11,Alex Crooks,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.00,15.0,player,2.0,NaN
12,Anthony Crooks,1.0,1.0,1.0,0.0,1.0,NaN,NaN,3.75,18.0,player,45.0,NaN
13,Syth Hargis,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.75,18.0,player,15.0,NaN
14,Katie Daeke,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.50,17.0,player,12.0,NaN
15,Jonah Vasquez,1.0,1.0,1.0,1.0,1.0,NaN,NaN,5.00,25.0,player,60.0,NaN
16,Michelle Vasquez,NaN,NaN,NaN,1.0,1.0,NaN,NaN,11.50,57.0,player,61.0,NaN
17,Kayla Loizzo,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,20.0,NaN
18,Marcell Benever,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,21.0,NaN
19,Randal Beachum,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.00,15.0,player,7.0,NaN
20,Richard Loomis,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.25,11.0,player,44.0,NaN
21,Justin Patzer,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,40.0,NaN
22,Shane Harrell,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,4.0,NaN
23,Malika Frisch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,player,NaN,NaN
24,Clifford Irons,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,NaN,NaN
25,Elizabeth Arnaiz,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,NaN,NaN
26,Dana Dyke,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,29.0,NaN
27,Sheila Dyke,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,player,30.0,NaN
28,Neil Godush,1.0,1.0,1.0,1.0,1.0,NaN,NaN,0.00,0.0,player,42.0,NaN
29,James Sherwin,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,18.0,NaN
30,Marina Lovell,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,player,NaN,NaN
31,Forest Jones,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.25,16.0,player,58.0,NaN
32,Gerald Shepherd,1.0,1.0,1.0,1.0,1.0,NaN,NaN,5.50,27.0,player,53.0,NaN
33,Aiden Smith,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,51.0,NaN
34,Jarett Batchelor,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,player,NaN,NaN
35,Laura Crooks,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.00,15.0,player,22.0,NaN
36,Tony Jones,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.50,12.0,player,23.0,NaN
37,Rebecca Seelig,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,player,NaN,NaN
38,Michael Truitt,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,player,NaN,NaN
39,Melissa Fulton,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.25,11.0,player,62.0,NaN
40,Joseph Perone,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,10.0,NaN
41,Nate Kargher,1.0,1.0,1.0,1.0,1.0,NaN,1.0,12.00,60.0,staff,6.0,NaN
42,AJ Eldred,1.0,1.0,1.0,1.0,1.0,NaN,NaN,4.00,20.0,staff,39.0,NaN
43,Tim Eldred,1.0,1.0,1.0,1.0,1.0,NaN,NaN,4.00,20.0,staff,43.0,NaN
44,Cody Archer,1.0,1.0,1.0,1.0,1.0,NaN,NaN,10.00,50.0,story,17.0,NaN
45,Robert Vasquez,1.0,1.0,1.0,1.0,1.0,NaN,NaN,10.00,50.0,story,26.0,NaN
46,AJ Thompson,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,9.0,NaN
47,Sarah Riviera,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,61.0,NaN
48,Dasia Elswick,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,16.0,NaN
49,Alyssa Warnock,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,24.0,NaN
50,Hannah Riviera,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,69.0,NaN
51,Jessica Leonard,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,staff,25.0,NaN
52,Eric West,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,1.0,NaN
53,Jon V,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,68.0,NaN

What we want the JSON to look like: 

```
{
   "rank":"staff",
   "paid":true,
   "checkin":true,
   "worked":true,
   "ap_earned":45,
   "ap_calculated":false,
   "character_id":1584,
   "user_id":26,
   "attended": true
},
```

In [28]:
# Needed variables 
rank = "staff"
paid = True 
checkin = True
worked = True 
ap_earned = 45
ap_calculated = False 
character_id = 1234
user_id = 26
attended = True

In [29]:
# Create a simple JSON structure
# Note: will need to add iterations as needed (ex: pillar_names[x])
One_JSON_Object = {"rank": rank, "paid": paid, "checkin": checkin, "worked": worked, "ap_earned": ap_earned, 
                  "ap_calculated": ap_calculated, "character_id": character_id, "user_id": user_id, "attended": attended}
# name = "name.json"
empty_test = []

# python_struct = json.loads(One_JSON_Object)
json_again = json.dumps(One_JSON_Object)

empty_test.append(json_again)

empty_test

['{"rank": "staff", "paid": true, "checkin": true, "worked": true, "ap_earned": 45, "ap_calculated": false, "character_id": 1234, "user_id": 26, "attended": true}']

## Gather the Variables Individually
### "rank"

In [6]:
df = pd.read_excel('Attendance and Payment April 2025.xlsx')
df = df.dropna(subset=["Attended"]).reset_index(drop=True)
df

,Name,Paid,Worked,Attended,18+,CoC,Cabin Number,Decorated,Hours Worked,AP Earned,Role,UserID,Notes
0,Maggie Holland,1.0,1.0,1.0,1.0,1.0,NaN,1.0,2.50,12.0,player,13.0,NaN
1,Jessica Remick,1.0,1.0,1.0,1.0,1.0,NaN,1.0,7.00,40.0,player,33.0,NaN
2,Todd Ladrach,1.0,1.0,1.0,1.0,1.0,NaN,NaN,4.00,20.0,player,NaN,NaN
3,Clay Westman,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.25,11.0,player,3.0,NaN
4,Matt Cuna,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,5.0,NaN
5,Blake Casanova,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,28.0,NaN
6,Alex Crooks,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.00,15.0,player,2.0,NaN
7,Anthony Crooks,1.0,1.0,1.0,0.0,1.0,NaN,NaN,3.75,18.0,player,45.0,NaN
8,Syth Hargis,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.75,18.0,player,15.0,NaN
9,Katie Daeke,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.50,17.0,player,12.0,NaN
10,Jonah Vasquez,1.0,1.0,1.0,1.0,1.0,NaN,NaN,5.00,25.0,player,60.0,NaN
11,Randal Beachum,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.00,15.0,player,7.0,NaN
12,Richard Loomis,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.25,11.0,player,44.0,NaN
13,Shane Harrell,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,4.0,NaN
14,Neil Godush,1.0,1.0,1.0,1.0,1.0,NaN,NaN,0.00,0.0,player,42.0,NaN
15,James Sherwin,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,18.0,NaN
16,Forest Jones,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.25,16.0,player,58.0,NaN
17,Gerald Shepherd,1.0,1.0,1.0,1.0,1.0,NaN,NaN,5.50,27.0,player,53.0,NaN
18,Aiden Smith,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,51.0,NaN
19,Laura Crooks,1.0,1.0,1.0,1.0,1.0,NaN,NaN,3.00,15.0,player,22.0,NaN
20,Tony Jones,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.50,12.0,player,23.0,NaN
21,Melissa Fulton,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.25,11.0,player,62.0,NaN
22,Joseph Perone,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.00,10.0,player,10.0,NaN
23,Nate Kargher,1.0,1.0,1.0,1.0,1.0,NaN,1.0,12.00,60.0,staff,6.0,NaN
24,AJ Eldred,1.0,1.0,1.0,1.0,1.0,NaN,NaN,4.00,20.0,staff,39.0,NaN
25,Tim Eldred,1.0,1.0,1.0,1.0,1.0,NaN,NaN,4.00,20.0,staff,43.0,NaN
26,Cody Archer,1.0,1.0,1.0,1.0,1.0,NaN,NaN,10.00,50.0,story,17.0,NaN
27,Robert Vasquez,1.0,1.0,1.0,1.0,1.0,NaN,NaN,10.00,50.0,story,26.0,NaN
28,AJ Thompson,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,9.0,NaN
29,Sarah Riviera,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,61.0,NaN
30,Dasia Elswick,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,16.0,NaN
31,Alyssa Warnock,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,24.0,NaN
32,Hannah Riviera,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,69.0,NaN
33,Jessica Leonard,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,staff,25.0,NaN
34,Eric West,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,1.0,NaN
35,Jon V,1.0,1.0,1.0,1.0,1.0,NaN,NaN,24.00,120.0,story,68.0,NaN

In [7]:
# For each row in df

for y in np.arange(0, len(df),1):
    rank = df["Role"][y]
    print(rank)

# df.columns

player
player
player
player
player
player
player
player
player
player
player
player
player
player
player
player
player
player
player
player
player
player
player
staff
staff
staff
story
story
story
story
story
story
story
staff
story
story

### "paid"

In [8]:
# for each row in df
for y in np.arange(0, len(df),1):
    paid = df["Paid"][y]

### "checkin"

In [10]:
# for each row in df 
for y in np.arange(0, len(df),1):
    checkin = df["Attended"][y]

### "worked"

In [11]:
# for each row in df
for y in np.arange(0, len(df),1):
    worked = df["Worked"][y]

### "ap_earned"

In [12]:
# for each row in df
for y in np.arange(0, len(df),1):
    ap_earned = int(df["AP Earned"][y])

### "ap_calculated"

In [36]:
ap_calculated = False

### "character_ID"

In [13]:
# for each row in df

for y in np.arange(0, len(df),1):
    character_id = df["CharacterID"][y]

KeyError: 'CharacterID'

### "user_id"

In [38]:
# for each row in df
for y in np.arange(0, len(df),1):
    user_id = int(df["UserID"][y])

### Remove "character_id" none

In [48]:
df = pd.read_excel('October 2023 Attendance and Payment.xlsx')
df = df.drop(columns = "Cabin Number").drop(columns = "Notes")
# df = df.dropna(subset=["CharacterID"]).reset_index()
# df = df.drop(columns = "index")
df = df[df['CharacterID'].isnull()]
df

,Name,Paid,Worked,Attended,18+,CoC,Decorated,Hours Worked,AP Earned,Role,UserID,CharacterID
1,Ryan Odell,1.0,NaN,NaN,True,True,NaN,NaN,10,player,NaN,NaN
2,Amanda Dalton,0.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
3,Chris Lynch,0.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
4,Emma Schaefer,1.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
5,Timothy Murphy,1.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
6,Elizabeth Arnaiz,1.0,NaN,1.0,True,True,NaN,2.0,10,player,NaN,NaN
7,Aiden Bork,1.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
8,Bernard Cecire,1.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
16,Kayla Loizzo,1.0,NaN,1.0,True,True,NaN,NaN,10,NaN,NaN,NaN
19,Chris Costello,1.0,NaN,1.0,True,True,NaN,NaN,10,staff,NaN,NaN
20,Ben Prihoda,0.0,NaN,1.0,True,True,NaN,NaN,10,NaN,NaN,NaN
22,Cody,NaN,NaN,1.0,True,True,NaN,NaN,10,story,NaN,NaN
23,Robert,NaN,NaN,1.0,True,True,NaN,NaN,10,story,NaN,NaN
27,Eric West,NaN,NaN,1.0,True,True,NaN,NaN,10,story,NaN,NaN
28,AJ Thompson,NaN,NaN,1.0,True,True,NaN,NaN,10,story,NaN,NaN
29,Jonah,NaN,NaN,1.0,True,True,NaN,NaN,10,stroy,NaN,NaN

## Put it All Together!

Note: Only run the imports once

In [1]:
import pandas as pd
import json 
import numpy as np 
import _pickle as pickle
import math

In [3]:
df = pd.read_csv('input/Attendance and Payment - 5_26 - Year3.csv')
# df = pd.read_excel('Attendance and Payment.xlsx')
df = df.dropna(subset=["Attended"]).reset_index(drop=True)
df = df.dropna(subset=["Name"]).reset_index(drop=True)
df = df[df["Paid"] == True].reset_index(drop=True)
df

,Name,Paid,Worked,Attended,18+,CoC,Cabin Number,Decorated,Hours Worked,AP Earned,Role,UserID,Notes
0,Maggie Cleary (Holland),True,True,True,True,True,NaN,False,2.0,10.0,player,13.0,Story Trainee
1,Clay Westman,True,False,True,True,True,NaN,False,NaN,NaN,player,3.0,NaN
2,Matt Cunha,True,True,True,True,True,NaN,False,5.0,45.0,player,5.0,"20 AP for tablet work, Tavern 3 hours, Story T..."
3,Marcell Benevento,True,False,True,True,True,NaN,False,2.5,132.0,player,21.0,"tavern, 2.5 hrs, $300 worth donated goods"
4,(Randle) Gorbash Beachum,True,True,True,True,True,NaN,False,11.0,55.0,player,7.0,"monstered 6hrs, site clean-up 5hrs"
5,Zephaniah Beachum,True,False,False,False,True,NaN,False,NaN,NaN,player,50.0,NaN
6,Richard Loomis,True,True,True,True,True,NaN,False,2.0,10.0,player,44.0,monstered 2hrs
7,Gerald Shepherd,True,True,True,True,True,NaN,False,2.0,10.0,player,53.0,monstered 2hrs
8,Aiden Smith,True,True,True,True,True,NaN,False,2.0,10.0,player,51.0,monstered 2 hrs
9,Shane Harrell,True,True,True,True,True,NaN,False,8.0,40.0,player,4.0,"medic, monstered 3 hrs, site clean-up 3hrs"
10,Jarett Batchelor,True,True,True,True,True,NaN,False,2.0,10.0,player,54.0,Tavern Clean-up 2 hrs
11,Nicholas Parker,True,True,True,True,True,NaN,False,4.0,20.0,player,72.0,"Tavern, 4 hrs"
12,Scott Benfield,True,True,True,True,True,NaN,False,7.0,40.0,player,80.0,"head of site clean-up, 7hrs"
13,David Louder,True,True,True,True,True,NaN,False,2.0,10.0,player,107.0,monstered 2hrs
14,(Brianna) Iggy Kale,True,True,True,False,True,NaN,False,2.0,10.0,player,123.0,"Tavern, 2 hrs"
15,(Lacey) Phayne Carrol,True,True,True,True,True,NaN,False,2.0,10.0,player,117.0,"Tavern, 2 hrs"
16,Jacob Womack,True,True,True,True,True,NaN,False,2.0,10.0,player,119.0,"Tavern, 2 hrs"
17,Eugene Smith,True,True,True,True,True,NaN,False,2.0,10.0,player,125.0,monsered 2hrs
18,Gary Hunter,True,True,True,True,True,NaN,False,4.5,22.0,player,120.0,"monstered 2hrs, tavern 2.5 hrs"
19,Sam Beveridge,True,True,True,True,True,NaN,False,2.0,10.0,player,106.0,monstered 2hrs
20,(Katelyn) Journey Ruggles,True,True,True,True,True,NaN,False,4.0,20.0,player,124.0,"Tavern, 4 hrs"
21,Jacob Walton,True,True,True,True,True,NaN,False,2.0,10.0,player,118.0,"Tavern, 2 hrs"
22,Gerald Judd,True,True,True,True,True,NaN,False,2.0,10.0,player,102.0,monstered 2hrs
23,Luke Young,True,True,True,True,True,NaN,False,3.5,17.0,player,76.0,"Tavern, 3.5 hrs"
24,Ethan King,True,True,True,True,True,NaN,False,2.0,20.0,player,133.0,monstered 2hrs. Bonus 10AP for bouncer duty.
25,(Taylor) Louis Guillot,True,True,True,False,True,NaN,False,2.0,10.0,player,132.0,"Tavern, 2 hrs"
26,(David) Taylor McFayden,True,True,True,True,True,NaN,False,2.0,10.0,player,135.0,monstered 2hrs
27,(David) Touska Pautke,True,True,True,True,True,NaN,False,24.0,120.0,staff,36.0,"medic, flunky"
28,Syth Hargis,True,True,True,True,True,NaN,False,24.0,120.0,staff,15.0,flunky
29,Jessica Remick,True,True,True,True,True,NaN,False,24.0,140.0,staff,33.0,"4 hrs for moving boxes, flunky, Story Trainee"
30,Jonah Vasquez,True,True,True,True,True,NaN,False,2.0,10.0,player,60.0,monstered 2hrs
31,Cody Archer,True,True,True,True,True,NaN,False,3.0,15.0,staff,17.0,"Schedule 1hr, monstered 2hrs"
32,Robert Vasquez,True,True,True,True,True,NaN,False,2.0,10.0,staff,26.0,monstered 2hrs
33,Sarah Riviera,True,True,True,True,True,NaN,False,2.0,10.0,staff,61.0,ran a mod
34,Hannah Riviera,True,True,True,True,True,NaN,False,2.0,10.0,staff,69.0,ran a mod
35,Nate Kargher,True,True,True,True,True,NaN,False,NaN,160.0,story,6.0,"4 hrs for moving boxes, 45 dollars of Radio, S..."
36,Alyssa Warnock,True,True,True,True,True,NaN,False,6.0,30.0,staff,24.0,"4 hrs for moving boxes, Tavern 2 hrs"
37,Galen Pischke,True,True,True,True,True,NaN,False,10.0,50.0,staff,64.0,"medic, tavern 9.5 hrs"
38,AJ Eldred,True,True,True,True,True,NaN,False,24.0,125.0,story,39.0,"Head medic, Head of Plot, donated goblets: $10"
39,Alex Winslow,True,True,True,True,True,NaN,False,NaN,120.0,story,65.0,Head of Tavern
40,Tim Eldred,True,True,True,True,True,NaN,False,NaN,120.0,story,43.0,Storyteller
41,AJ Thompson,True,True,True,True,True,NaN,False,NaN,120.0,story,9.0,Plot XO
42,Eric West,True,True,True,True,True,NaN,False,NaN,120.0,story,1.0,Sysadmin
43,Jon V,True,True,False,True,True,NaN,False,NaN,NaN,player,68.0,RIP

In [4]:
ap_calculated = bool(False)
attendance_JSON = []
month = "May Check "
year = "2026"

for y in np.arange(0, len(df),1):
    rank = str(df["Role"][y])
    paid = bool(df["Paid"][y])
    checkin = bool(df["Attended"][y])
    attended = bool(df["Attended"][y])
    worked = bool(df["Worked"][y])
    ap_earned = 0 if pd.isna(df["AP Earned"][y]) else int(df["AP Earned"][y])
    user_id = int(df["UserID"][y])
    
    # Create the JSON Object 
    One_JSON_Object = {"rank": rank, 
                       "paid": paid, 
                       "checkin": checkin, 
                       "worked": worked, 
                       "ap_earned": ap_earned, 
                       "ap_calculated": ap_calculated, 
                       "user_id": user_id, 
                       "attended": attended}
    
    attendance_JSON.append(One_JSON_Object)
    
        
file_name = month + year + "_attendance.json"

json_again = json.dumps(attendance_JSON)

with open(file_name, 'w') as f:
    f.write(json_again)
    
print(f"{file_name} created")

May Check 2026_attendance.json created

# "Incomplete Attendance" Script Below

In [6]:
df = pd.read_excel('Attendance and Payment May 2024.xlsx')
df = df.drop(columns = "Cabin Number").drop(columns = "Notes")
df = df[df['CharacterID'].notnull()]
df.fillna(value="Null", inplace=True)
df

,Name,Paid,Worked,Attended,18+,CoC,Decorated,Hours Worked,AP Earned,Role,UserID,CharacterID
0,Matt Cuna,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,6.0,1407.0
1,Emma Schaefer,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,57.0,2115.0
2,Bernard Cecire,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,46.0,2065.0
3,Nate Kargher,1.0,1.0,1.0,1.0,1.0,Null,6.0,30.0,player,36.0,1810.0
4,Wes Holland,1.0,1.0,1.0,1.0,1.0,1.0,2.0,15.0,player,10.0,1422.0
5,Maggie Holland,1.0,1.0,1.0,1.0,1.0,1.0,2.0,10.0,player,35.0,1814.0
6,James Albrikes,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,31.0,1664.0
7,Lydia Albrikes,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,32.0,1673.0
8,Clay Westman,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,9.0,1798.0
9,Todd Ladrach,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,39.0,2090.0
10,Alyssa Warnock,1.0,1.0,1.0,1.0,1.0,Null,4.0,20.0,player,26.0,1584.0
11,Blake Casanova,1.0,1.0,1.0,1.0,1.0,Null,3.0,15.0,player,60.0,2235.0
12,Walter Bunge,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,84.0,2842.0
13,David Pautke,1.0,1.0,0.0,1.0,1.0,Null,2.0,0.0,player,79.0,2789.0
14,Alex Crooks,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,73.0,2620.0
15,Anthony,1.0,1.0,1.0,0.0,1.0,Null,6.0,10.0,player,75.0,2755.0
16,Syth Hargis,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,76.0,2727.0
17,Jessica Remick,1.0,1.0,1.0,1.0,1.0,Null,8.0,40.0,player,64.0,2273.0
18,Netty Torres,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,72.0,2849.0
19,Mike Warnock,1.0,1.0,1.0,1.0,1.0,Null,2.0,10.0,player,22.0,1548.0
24,Dasia Elswick,Null,Null,1.0,1.0,1.0,Null,2.0,Null,staff,7.0,1411.0
25,Hannah Riviera,1.0,Null,Null,1.0,1.0,Null,4.0,Null,staff,27.0,1716.0
26,Sarah Riviera,1.0,Null,Null,1.0,1.0,Null,2.0,Null,staff,8.0,1696.0
28,AJ Thompson,Null,Null,1.0,1.0,1.0,Null,2.0,Null,staff,16.0,2607.0

In [68]:
# Load the Excel file into a DataFrame
df = pd.read_excel('October 2023 Attendance and Payment.xlsx')

# Drop unnecessary columns
df = df.drop(columns=["Cabin Number", "Notes"])

# Filter rows where CharacterID is null
df = df[df['CharacterID'].isnull()]

# Initialize variables
ap_calculated = bool(False)
attendance_JSON = []
month = "October "
year = "2023 Incomplete"

# Loop through DataFrame rows
for index, row in df.iterrows():
    rank = row["Role"]
    paid = bool(row["Paid"])
    checkin = bool(row["Attended "])
    attended = bool(row["Attended "])  # Assuming this is intentional
    worked = bool(row["Worked"])
    ap_earned = int(row["AP Earned"])
    user_id = None
    character_id = None  # You're filtering by null CharacterID, so it's None
    
    # Create the JSON Object 
    one_json_object = {
        "rank": rank,
        "paid": paid,
        "checkin": checkin,
        "worked": worked,
        "ap_earned": ap_earned,
        "ap_calculated": ap_calculated,
        "character_id": character_id,
        "user_id": user_id,
        "attended": attended
    }
    
    attendance_JSON.append(one_json_object)

# Write JSON data to a file
file_name = month + year + "_attendance.json"
with open(file_name, 'w') as f:
    json.dump(attendance_JSON, f)

print(f"{file_name} created")

October 2023 Incomplete_attendance.json created