# Five Pillars JSON 
This is for Attendance

## Loop through all Attendance for one user_id

Make a JSON array of : 
```
        
       {
            "rank": rank,
            "paid": paid,
            "checkin": checkin,
            "worked": worked,
            "ap_earned": ap_earned,
            "ap_calculated": ap_calculated,
            "user_id": user_id,
            "attended": attended,
            "event_id": event_id
        }, 
            {
            "rank": rank,
            "paid": paid,
            "checkin": checkin,
            "worked": worked,
            "ap_earned": ap_earned,
            "ap_calculated": ap_calculated,
            "user_id": user_id,
            "attended": attended,
            "event_id": event_id
        }
etc...
```
For each attendance.  The output file should be the person's name.

Important: Make sure you update the person's names to be consistent between files.

In [2]:
import pandas as pd
import numpy as np
import json
import math

# Load the Excel file
file_path = 'input/Attendance and Payment Updated Final.xlsx'
excel_file = pd.ExcelFile(file_path)

# Dictionary to store attendance records per name
attendance_records = {}
event_id = 3

# Loop through each sheet name
for sheet_name in excel_file.sheet_names:
    df = excel_file.parse(sheet_name)
    event_id += 1 

    # Skip the sheet if "Name" column is missing
    if "Name" not in df.columns:
        print(f"Skipping sheet '{sheet_name}' as 'Name' column is missing.")
        continue

    # Drop rows where "Name" is NaN or empty
    df = df.dropna(subset=["Name"])

    # Skip sheet if no valid names are found
    if df.empty:
        print(f"Skipping sheet '{sheet_name}' as it contains no valid names.")
        continue

    # Loop through each row in the DataFrame
    for _, row in df.iterrows():
        name = row["Name"]

        # Skip if name is NaN or empty
        if pd.isna(name) or name == "":
            continue

        # Extract values, handling NaN cases
        rank = row["Role"]
        paid = bool(row["Paid"])
        checkin = bool(row["Attended "])
        attended = bool(row["Attended "])
        worked = bool(row["Worked"])
        ap_earned = int(row["AP Earned"]) if not pd.isna(row["AP Earned"]) else 0
        ap_calculated = bool(False)
        user_id = int(row["UserID"])

        # Create the JSON object for the record
        record = {
            "rank": rank,
            "paid": paid,
            "checkin": checkin,
            "worked": worked,
            "ap_earned": ap_earned,
            "ap_calculated": ap_calculated,
            "user_id": user_id,
            "attended": attended,
            "event_id": event_id
        }

        # Append record to the name's list in the dictionary
        if name not in attendance_records:
            attendance_records[name] = []
        attendance_records[name].append(record)

# Save each name's records to a JSON file
for name, records in attendance_records.items():
    file_name = f"{name} attendance.json"
    with open('output/'+ file_name, 'w') as f:
        json.dump(records, f, indent=4)

    print(f"{file_name} created")

Matt Cuna attendance.json created
Mark Zaverukha attendance.json created
Patrick Moss attendance.json created
Azlynn Moss attendance.json created
Dasia Elswick attendance.json created
Wes Holland attendance.json created
Maggie Holland attendance.json created
James Albrikes attendance.json created
Lydia Albrikes attendance.json created
Alyssa Warnock attendance.json created
Joel Batista attendance.json created
Hannah Riviera attendance.json created
Marcell Benever attendance.json created
Sarah Riviera attendance.json created
Clay Westman attendance.json created
Chris Costello attendance.json created
Katherine Parkerson attendance.json created
Samael Hamlet attendance.json created
Mike Warnock attendance.json created
Cody Archer attendance.json created
Robert Vasquez attendance.json created
Eric West attendance.json created
Jon Vasquez attendance.json created
AJ Thompson attendance.json created
Tim Eldred attendance.json created
Alex Winslow attendance.json created
AJ Eldred attendance.json created
Galen Pishke attendance.json created
Nate Kargher attendance.json created
Dani Hauck attendance.json created
Todd Ladrach attendance.json created
Jordan Rock attendance.json created
Jonah Vasquez attendance.json created
Ryan Odell attendance.json created
Amanda Dalton attendance.json created
Chris Lynch attendance.json created
Emma Schaefer attendance.json created
Timothy Murphy attendance.json created
Elizabeth Arnaiz attendance.json created
Aiden Bork attendance.json created
Bernard Cecire attendance.json created
Kayla Loizzo attendance.json created
Ben Prihoda attendance.json created
Blake Casanova attendance.json created
Walter Bunge attendance.json created
David Pautke attendance.json created
Alex Crooks attendance.json created
Anthony Crooks attendance.json created
Syth Hargis attendance.json created
Jessica Remick attendance.json created
Netty Torres attendance.json created
Kaylun Bolt attendance.json created
Dana Dyke attendance.json created
Sheila Dyke attendance.json created
Randal Beachum attendance.json created
Katie Daeke attendance.json created
Karissa Martinez attendance.json created
Shannon Thornhill attendance.json created
Nick Foster attendance.json created
Jessica Leonard attendance.json created
Michelle Vasquez attendance.json created
Dakota Traeger attendance.json created
Kriss Sakurai attendance.json created
Richard Loomis attendance.json created
Justin Patzer attendance.json created
Shane Harrell  attendance.json created
Malika Frisch attendance.json created
Clifford Irons attendance.json created

## Single Attendance Sheet JSON Loop
This loop below will take a single Excel file with only one sheet and will output the following JSON: 

```
{
   "rank":"staff",
   "paid":true,
   "checkin":true,
   "worked":true,
   "ap_earned":45,
   "ap_calculated":false,
   "character_id":1584,
   "user_id":26,
   "attended": true
},
```

In [2]:
import pandas as pd
import json 
import numpy as np 
import _pickle as pickle
import math

## INPUTS HERE
df = pd.read_excel('Attendance and Payment October 2024.xlsx')
month = "April "
year = "2026"

## END OF INPUTS

df = df.drop(columns = "Cabin Number").drop(columns = "Notes")
df = df.dropna(subset=["CharacterID"]).reset_index()
df = df.drop(columns = "index")
ap_calculated = bool(False)
attendance_JSON = []

for y in np.arange(0, len(df),1):
    rank = df["Role"][y]
    paid = bool(df["Paid"][y])
    checkin = bool(df["Attended "][y])
    attended = bool(df["Attended "][y])
    worked = bool(df["Worked"][y])
    ap_earned = int(df["AP Earned"][y]) if not math.isnan(df["AP Earned"][y]) else 0
    user_id = int(df["UserID"][y])
    character_id = int(df["CharacterID"][y])
    
    # Create the JSON Object 
    One_JSON_Object = {"rank": rank, "paid": paid, "checkin": checkin, "worked": worked, "ap_earned": ap_earned, 
                  "ap_calculated": ap_calculated, "character_id": character_id, "user_id": user_id, "attended": attended}
    
    attendance_JSON.append(One_JSON_Object)
    
        
file_name = month + year + "_attendance.json"

json_again = json.dumps(attendance_JSON)

with open(file_name, 'w') as f:
    f.write(json_again)
    
print(f"{file_name} created")

October 2024_attendance.json created

## Working Parts
Below is the individual working parts for your loop

What we want the JSON to look like: 

```
{
   "rank":"staff",
   "paid":true,
   "checkin":true,
   "worked":true,
   "ap_earned":45,
   "ap_calculated":false,
   "character_id":1584,
   "user_id":26,
   "attended": true
},
```

In [2]:
import pandas as pd
import json 
import numpy as np 
import _pickle as pickle
import math

In [2]:
# Pull in the df
df = pd.read_excel('October 2023 Attendance and Payment.xlsx')
df

,Name,Paid,Worked,Attended,18+,CoC,Cabin Number,Decorated,Hours Worked,AP Earned,Role,UserID,CharacterID,Notes
0,Matt Cuna,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,6.0,1407.0,NaN
1,Ryan Odell,1.0,NaN,NaN,True,True,NaN,NaN,NaN,NaN,player,NaN,NaN,NaN
2,Amanda Dalton,0.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,NaN,NaN,NaN
3,Chris Lynch,0.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,NaN,NaN,NaN
4,Emma Schaefer,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,NaN,NaN,NaN
5,Timothy Murphy,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,NaN,NaN,NaN
6,Elizabeth Arnaiz,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,NaN,NaN,NaN
7,Aiden Bork,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,NaN,NaN,NaN
8,Bernard Cecire,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,NaN,NaN,NaN
9,Nate Kargher,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,36.0,1810.0,NaN
10,Mike Warnock,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,22.0,1548.0,NaN
11,Wes Holland,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,10.0,1422.0,NaN
12,Maggie Holland,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,35.0,1814.0,NaN
13,James Albrikes,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,31.0,1664.0,NaN
14,Lydia Albrikes,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,32.0,1673.0,NaN
15,Marcell Benever,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,12.0,1442.0,NaN
16,Kayla Loizzo,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Clay Westman,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,9.0,1798.0,NaN
18,Todd Ladrach,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,player,39.0,2090.0,NaN
19,Chris Costello,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,staff,NaN,NaN,NaN
20,Ben Prihoda,0.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Alyssa Warnock,1.0,NaN,1.0,True,True,NaN,NaN,NaN,NaN,staff,26.0,1584.0,NaN
22,Cody,NaN,NaN,1.0,True,True,NaN,NaN,NaN,NaN,story,NaN,NaN,NaN
23,Robert,NaN,NaN,1.0,True,True,NaN,NaN,NaN,NaN,story,NaN,NaN,NaN
24,Dasia Elswick,NaN,NaN,1.0,True,True,NaN,NaN,NaN,NaN,story,7.0,1411.0,NaN
25,Hannah Riviera,NaN,NaN,1.0,True,True,NaN,NaN,NaN,NaN,story,27.0,1716.0,NaN
26,Sarah Riviera,NaN,NaN,1.0,True,True,NaN,NaN,NaN,NaN,story,8.0,1696.0,NaN
27,Eric West,NaN,NaN,1.0,True,True,NaN,NaN,NaN,NaN,story,NaN,NaN,NaN
28,AJ Thompson,NaN,NaN,1.0,True,True,NaN,NaN,NaN,NaN,story,NaN,NaN,NaN
29,Jonah,NaN,NaN,1.0,True,True,NaN,NaN,NaN,NaN,stroy,NaN,NaN,NaN

In [28]:
# Needed variables 
rank = "staff"
paid = True 
checkin = True
worked = True 
ap_earned = 45
ap_calculated = False 
character_id = 1234
user_id = 26
attended = True

In [29]:
# Create a simple JSON structure
# Note: will need to add iterations as needed (ex: pillar_names[x])
One_JSON_Object = {"rank": rank, "paid": paid, "checkin": checkin, "worked": worked, "ap_earned": ap_earned, 
                  "ap_calculated": ap_calculated, "character_id": character_id, "user_id": user_id, "attended": attended}
# name = "name.json"
empty_test = []

# python_struct = json.loads(One_JSON_Object)
json_again = json.dumps(One_JSON_Object)

empty_test.append(json_again)

empty_test

['{"rank": "staff", "paid": true, "checkin": true, "worked": true, "ap_earned": 45, "ap_calculated": false, "character_id": 1234, "user_id": 26, "attended": true}']

## Gather the Variables Individually
### "rank"

In [30]:
df = pd.read_excel('October 2023 Attendance and Payment.xlsx')
df = df.dropna().reset_index()
# df

In [31]:
# For each row in df

for y in np.arange(0, len(df),1):
    rank = df["Role"][y]
    # print(rank)

# df.columns

### "paid"

In [32]:
# for each row in df
for y in np.arange(0, len(df),1):
    paid = df["Paid"][y]

### "checkin"

In [33]:
# for each row in df 
for y in np.arange(0, len(df),1):
    checkin = df["Attended "][y]

### "worked"

In [34]:
# for each row in df
for y in np.arange(0, len(df),1):
    worked = df["Worked"][y]

### "ap_earned"

In [35]:
# for each row in df
for y in np.arange(0, len(df),1):
    ap_earned = int(df["AP Earned"][y])

### "ap_calculated"

In [36]:
ap_calculated = False

### "character_ID"

In [37]:
# for each row in df

for y in np.arange(0, len(df),1):
    character_id = df["CharacterID"][y]

### "user_id"

In [38]:
# for each row in df
for y in np.arange(0, len(df),1):
    user_id = int(df["UserID"][y])

### Remove "character_id" none

In [48]:
df = pd.read_excel('October 2023 Attendance and Payment.xlsx')
df = df.drop(columns = "Cabin Number").drop(columns = "Notes")
# df = df.dropna(subset=["CharacterID"]).reset_index()
# df = df.drop(columns = "index")
df = df[df['CharacterID'].isnull()]
df

,Name,Paid,Worked,Attended,18+,CoC,Decorated,Hours Worked,AP Earned,Role,UserID,CharacterID
1,Ryan Odell,1.0,NaN,NaN,True,True,NaN,NaN,10,player,NaN,NaN
2,Amanda Dalton,0.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
3,Chris Lynch,0.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
4,Emma Schaefer,1.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
5,Timothy Murphy,1.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
6,Elizabeth Arnaiz,1.0,NaN,1.0,True,True,NaN,2.0,10,player,NaN,NaN
7,Aiden Bork,1.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
8,Bernard Cecire,1.0,NaN,1.0,True,True,NaN,NaN,10,player,NaN,NaN
16,Kayla Loizzo,1.0,NaN,1.0,True,True,NaN,NaN,10,NaN,NaN,NaN
19,Chris Costello,1.0,NaN,1.0,True,True,NaN,NaN,10,staff,NaN,NaN
20,Ben Prihoda,0.0,NaN,1.0,True,True,NaN,NaN,10,NaN,NaN,NaN
22,Cody,NaN,NaN,1.0,True,True,NaN,NaN,10,story,NaN,NaN
23,Robert,NaN,NaN,1.0,True,True,NaN,NaN,10,story,NaN,NaN
27,Eric West,NaN,NaN,1.0,True,True,NaN,NaN,10,story,NaN,NaN
28,AJ Thompson,NaN,NaN,1.0,True,True,NaN,NaN,10,story,NaN,NaN
29,Jonah,NaN,NaN,1.0,True,True,NaN,NaN,10,stroy,NaN,NaN

## Put it All Together!

In [1]:
import pandas as pd
import json 
import numpy as np 
import _pickle as pickle
import math

In [5]:
# df = pd.read_excel('Attendance and Payment')
df = pd.read_csv('input/Attendance and Payment - 5_26 - Year3.csv')
df = df.dropna(subset=["Attended"]).reset_index(drop=True)
df = df.dropna(subset=["Name"]).reset_index(drop=True)
df = df[df["Paid"] == True].reset_index(drop=True)
df

,Name,Paid,Worked,Attended,18+,CoC,Cabin Number,Decorated,Hours Worked,AP Earned,Role,UserID,Notes
0,Maggie Cleary (Holland),True,True,True,True,True,NaN,False,2.0,10.0,player,13.0,Story Trainee
1,Clay Westman,True,False,True,True,True,NaN,False,NaN,NaN,player,3.0,NaN
2,Matt Cunha,True,True,True,True,True,NaN,False,5.0,45.0,player,5.0,"20 AP for tablet work, Tavern 3 hours, Story T..."
3,Marcell Benevento,True,False,True,True,True,NaN,False,2.5,132.0,player,21.0,"tavern, 2.5 hrs, $300 worth donated goods"
4,(Randle) Gorbash Beachum,True,True,True,True,True,NaN,False,11.0,55.0,player,7.0,"monstered 6hrs, site clean-up 5hrs"
5,Zephaniah Beachum,True,False,False,False,True,NaN,False,NaN,NaN,player,50.0,NaN
6,Richard Loomis,True,True,True,True,True,NaN,False,2.0,10.0,player,44.0,monstered 2hrs
7,Gerald Shepherd,True,True,True,True,True,NaN,False,2.0,10.0,player,53.0,monstered 2hrs
8,Aiden Smith,True,True,True,True,True,NaN,False,2.0,10.0,player,51.0,monstered 2 hrs
9,Shane Harrell,True,True,True,True,True,NaN,False,8.0,40.0,player,4.0,"medic, monstered 3 hrs, site clean-up 3hrs"
10,Jarett Batchelor,True,True,True,True,True,NaN,False,2.0,10.0,player,54.0,Tavern Clean-up 2 hrs
11,Nicholas Parker,True,True,True,True,True,NaN,False,4.0,20.0,player,72.0,"Tavern, 4 hrs"
12,Scott Benfield,True,True,True,True,True,NaN,False,7.0,40.0,player,80.0,"head of site clean-up, 7hrs"
13,David Louder,True,True,True,True,True,NaN,False,2.0,10.0,player,107.0,monstered 2hrs
14,(Brianna) Iggy Kale,True,True,True,False,True,NaN,False,2.0,10.0,player,123.0,"Tavern, 2 hrs"
15,(Lacey) Phayne Carrol,True,True,True,True,True,NaN,False,2.0,10.0,player,117.0,"Tavern, 2 hrs"
16,Jacob Womack,True,True,True,True,True,NaN,False,2.0,10.0,player,119.0,"Tavern, 2 hrs"
17,Eugene Smith,True,True,True,True,True,NaN,False,2.0,10.0,player,125.0,monsered 2hrs
18,Gary Hunter,True,True,True,True,True,NaN,False,4.5,22.0,player,120.0,"monstered 2hrs, tavern 2.5 hrs"
19,Sam Beveridge,True,True,True,True,True,NaN,False,2.0,10.0,player,106.0,monstered 2hrs
20,(Katelyn) Journey Ruggles,True,True,True,True,True,NaN,False,4.0,20.0,player,124.0,"Tavern, 4 hrs"
21,Jacob Walton,True,True,True,True,True,NaN,False,2.0,10.0,player,118.0,"Tavern, 2 hrs"
22,Gerald Judd,True,True,True,True,True,NaN,False,2.0,10.0,player,102.0,monstered 2hrs
23,Luke Young,True,True,True,True,True,NaN,False,3.5,17.0,player,76.0,"Tavern, 3.5 hrs"
24,Ethan King,True,True,True,True,True,NaN,False,2.0,20.0,player,133.0,monstered 2hrs. Bonus 10AP for bouncer duty.
25,(Taylor) Louis Guillot,True,True,True,False,True,NaN,False,2.0,10.0,player,132.0,"Tavern, 2 hrs"
26,(David) Taylor McFayden,True,True,True,True,True,NaN,False,2.0,10.0,player,135.0,monstered 2hrs
27,(David) Touska Pautke,True,True,True,True,True,NaN,False,24.0,120.0,staff,36.0,"medic, flunky"
28,Syth Hargis,True,True,True,True,True,NaN,False,24.0,120.0,staff,15.0,flunky
29,Jessica Remick,True,True,True,True,True,NaN,False,24.0,140.0,staff,33.0,"4 hrs for moving boxes, flunky, Story Trainee"
30,Jonah Vasquez,True,True,True,True,True,NaN,False,2.0,10.0,player,60.0,monstered 2hrs
31,Cody Archer,True,True,True,True,True,NaN,False,3.0,15.0,staff,17.0,"Schedule 1hr, monstered 2hrs"
32,Robert Vasquez,True,True,True,True,True,NaN,False,2.0,10.0,staff,26.0,monstered 2hrs
33,Sarah Riviera,True,True,True,True,True,NaN,False,2.0,10.0,staff,61.0,ran a mod
34,Hannah Riviera,True,True,True,True,True,NaN,False,2.0,10.0,staff,69.0,ran a mod
35,Nate Kargher,True,True,True,True,True,NaN,False,NaN,160.0,story,6.0,"4 hrs for moving boxes, 45 dollars of Radio, S..."
36,Alyssa Warnock,True,True,True,True,True,NaN,False,6.0,30.0,staff,24.0,"4 hrs for moving boxes, Tavern 2 hrs"
37,Galen Pischke,True,True,True,True,True,NaN,False,10.0,50.0,staff,64.0,"medic, tavern 9.5 hrs"
38,AJ Eldred,True,True,True,True,True,NaN,False,24.0,125.0,story,39.0,"Head medic, Head of Plot, donated goblets: $10"
39,Alex Winslow,True,True,True,True,True,NaN,False,NaN,120.0,story,65.0,Head of Tavern
40,Tim Eldred,True,True,True,True,True,NaN,False,NaN,120.0,story,43.0,Storyteller
41,AJ Thompson,True,True,True,True,True,NaN,False,NaN,120.0,story,9.0,Plot XO
42,Eric West,True,True,True,True,True,NaN,False,NaN,120.0,story,1.0,Sysadmin
43,Jon V,True,True,False,True,True,NaN,False,NaN,NaN,player,68.0,RIP

In [6]:
ap_calculated = bool(False)
attendance_JSON = []
month = "May "
year = "2026"

for y in np.arange(0, len(df),1):
    rank = str(df["Role"][y])
    paid = bool(df["Paid"][y])
    checkin = bool(df["Attended"][y])
    attended = bool(df["Attended"][y])
    worked = bool(df["Worked"][y])
    ap_earned = 0 if pd.isna(df["AP Earned"][y]) else int(df["AP Earned"][y])
    user_id = int(df["UserID"][y])
    
    # Create the JSON Object 
    One_JSON_Object = {"rank": rank, 
                       "paid": paid, 
                       "checkin": checkin, 
                       "worked": worked, 
                       "ap_earned": ap_earned, 
                       "ap_calculated": ap_calculated, 
                       "user_id": user_id, 
                       "attended": attended}
    
    attendance_JSON.append(One_JSON_Object)
    
        
file_name = month + year + "_attendance.json"

json_again = json.dumps(attendance_JSON)

with open(file_name, 'w') as f:
    f.write(json_again)
    
print(f"{file_name} created")

May 2026_attendance.json created

## Incomplete Script below

In [68]:
# Load the Excel file into a DataFrame
df = pd.read_excel('October 2023 Attendance and Payment.xlsx')

# Drop unnecessary columns
df = df.drop(columns=["Cabin Number", "Notes"])

# Filter rows where CharacterID is null
df = df[df['CharacterID'].isnull()]

# Initialize variables
ap_calculated = bool(False)
attendance_JSON = []
month = "October "
year = "2023 Incomplete"

# Loop through DataFrame rows
for index, row in df.iterrows():
    rank = row["Role"]
    paid = bool(row["Paid"])
    checkin = bool(row["Attended "])
    attended = bool(row["Attended "])  # Assuming this is intentional
    worked = bool(row["Worked"])
    ap_earned = int(row["AP Earned"])
    user_id = None
    character_id = None  # You're filtering by null CharacterID, so it's None
    
    # Create the JSON Object 
    one_json_object = {
        "rank": rank,
        "paid": paid,
        "checkin": checkin,
        "worked": worked,
        "ap_earned": ap_earned,
        "ap_calculated": ap_calculated,
        "character_id": character_id,
        "user_id": user_id,
        "attended": attended
    }
    
    attendance_JSON.append(one_json_object)

# Write JSON data to a file
file_name = month + year + "_attendance.json"
with open(file_name, 'w') as f:
    json.dump(attendance_JSON, f)

print(f"{file_name} created")

October 2023 Incomplete_attendance.json created